use_frameworks!

platform :ios, '11.0'

target 'Nimble-SnapshotTesting_Example' do
  target 'Nimble-SnapshotTesting_Tests' do
    inherit! :search_paths

    pod 'Nimble-SnapshotTesting', :path => '../'
    pod 'Quick', '~> 3.0.0'
    pod 'Nimble', '~> 9.2.1'
  end
end
