use_frameworks!

platform :ios, '13.0'

target 'Nimble-SnapshotTesting_Example' do
  target 'Nimble-SnapshotTesting_Tests' do
    inherit! :search_paths

    pod 'SnapshotTesting'
    pod 'Nimble-SnapshotTesting', :path => '../'
    pod 'Quick', '~> 7'
    pod 'Nimble', '~> 13.0.0'
  end
end
